name: Daily Job Search

on:
  workflow_dispatch:

  schedule:
    - cron: '30 4 * * *'

permissions:
  contents: write

jobs:
  search:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python scripts/fetch_jobs.py

      - name: Commit updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/jobs.csv data/raw_jobs.csv
          git diff --staged --quiet || git commit -m "Update jobs data"
          git push
